# Generated by Django 4.2.5 on 2023-10-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='tag',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='anime.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producer', to='anime.producer'),
        ),
        migrations.AddField(
            model_name='anime',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='anime.animetag'),
        ),
    ]
