# Generated by Django 4.2.5 on 2023-10-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_genre_remove_anime_producer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='basis',
        ),
        migrations.DeleteModel(
            name='Basis',
        ),
    ]
