# Generated by Django 4.2.5 on 2023-10-04 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_anime_basis_delete_basis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='tag',
        ),
        migrations.CreateModel(
            name='AnimeTagTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.anime')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.animetag')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='tag',
            field=models.ManyToManyField(related_query_name='tags', through='anime.AnimeTagTable', to='anime.animetag'),
        ),
    ]
