# Generated by Django 4.2.5 on 2023-10-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_remove_anime_tag_animetagtable_anime_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='year',
        ),
        migrations.CreateModel(
            name='AnimeYearsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.anime')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.years')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeProducerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.anime')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.producer')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeGenreTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.anime')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.genre')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(related_name='genre', through='anime.AnimeGenreTable', to='anime.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='producer',
            field=models.ManyToManyField(related_name='producer', through='anime.AnimeProducerTable', to='anime.producer'),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.ManyToManyField(related_name='year', through='anime.AnimeYearsTable', to='anime.years'),
        ),
    ]
