# Generated by Django 4.2.5 on 2023-10-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_remove_anime_genre_remove_anime_producer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seiyuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='seiyuu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='anime.seiyuu'),
        ),
    ]
