# Generated by Django 4.2.5 on 2023-10-04 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_seiyuu_alter_character_seiyuu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='year',
        ),
        migrations.DeleteModel(
            name='AnimeYearsTable',
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='year', to='anime.years'),
        ),
    ]
