# Generated by Django 4.2.5 on 2023-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_alter_anime_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seiyuu',
            name='seiyuu_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
