# Generated by Django 4.2.5 on 2023-10-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_author_author_slug_genre_genre_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='seiyuu',
            name='seiyuu_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
