# Generated by Django 4.2.5 on 2023-10-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_alter_author_author_slug_alter_genre_genre_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='anime.studio'),
        ),
    ]
