# Generated by Django 4.2.5 on 2023-10-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_anime_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetag',
            name='tag_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
