# Generated by Django 4.2.5 on 2023-10-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_animetag_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animetag',
            name='tag_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
